version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: food_api_prod
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://admin:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/food_delivery?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
    networks:
      - backend

  mongo:
    image: mongo:7.0
    container_name: food_mongo_prod
    # порт 27017 НЕ проброшен наружу в проде
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: always
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge